name: "Docs (dev) - main branch"
on:
  push:
    branches: ["main"]
permissions:
  contents: write
concurrency:
  group: docs
  cancel-in-progress: false
jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: git fetch origin gh-pages --depth=1 || true
      - uses: actions/setup-python@v5
        with: { python-version: "3.x" }
      - run: |
          pip install -r requirements.txt
      - name: "Deploy dev version (no alias, no default)"
        run: |
          set -euxo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mike deploy --push --branch gh-pages dev
          # NOTE: no --update-aliases and no set-default here

